"""Add question_responses table

Revision ID: 6c2465c2bdeb
Revises: e3054c4a5096
Create Date: 2025-04-25 08:29:32.377742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2465c2bdeb'
down_revision = 'e3054c4a5096'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_text', sa.Text(), nullable=True))
        batch_op.drop_column('response')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.TEXT(), nullable=True))
        batch_op.drop_column('response_text')

    # ### end Alembic commands ###
