"""Add start_date, end_date, budget, sector fields to Project model

Revision ID: a65746a4f325
Revises: 9e8d1a2f42c6
Create Date: 2025-05-14 14:04:14.744124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a65746a4f325'
down_revision = '9e8d1a2f42c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_sdg_relationships')
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('assessment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'standard'"))

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))

    with op.batch_alter_table('sdg_relationships', schema=None) as batch_op:
        batch_op.alter_column('strength',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('relationship_strength')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sdg_relationships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relationship_strength', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.alter_column('strength',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('sector')
        batch_op.drop_column('budget')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')

    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.alter_column('assessment_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'standard'"))

    op.create_table('_alembic_tmp_sdg_relationships',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('strength', sa.FLOAT(), nullable=False),
    sa.Column('source_sdg_id', sa.INTEGER(), nullable=True),
    sa.Column('target_sdg_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['source_sdg_id'], ['sdg_goals.id'], ),
    sa.ForeignKeyConstraint(['target_sdg_id'], ['sdg_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
