"""Clean initial migration

Revision ID: a67153dd301b
Revises: 
Create Date: 2025-04-24 21:29:44.350443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a67153dd301b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdg_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color_code', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('size_sqm', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdg_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('sdg_id', sa.Integer(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sdg_id'], ['sdg_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdg_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_sdg_id', sa.Integer(), nullable=True),
    sa.Column('target_sdg_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_sdg_id'], ['sdg_goals.id'], ),
    sa.ForeignKeyConstraint(['target_sdg_id'], ['sdg_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('step1_completed', sa.Boolean(), nullable=True),
    sa.Column('step2_completed', sa.Boolean(), nullable=True),
    sa.Column('step3_completed', sa.Boolean(), nullable=True),
    sa.Column('step4_completed', sa.Boolean(), nullable=True),
    sa.Column('step5_completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sdg_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('sdg_id', sa.Integer(), nullable=False),
    sa.Column('direct_score', sa.Float(), nullable=True),
    sa.Column('bonus_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('raw_score', sa.Float(), nullable=True),
    sa.Column('max_possible', sa.Float(), nullable=True),
    sa.Column('percentage_score', sa.Float(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['sdg_id'], ['sdg_goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdg_scores')
    op.drop_table('assessments')
    op.drop_table('sdg_relationships')
    op.drop_table('sdg_questions')
    op.drop_table('projects')
    op.drop_table('user')
    op.drop_table('sdg_goals')
    # ### end Alembic commands ###
