"""add share_token and share_expires to assessments

Revision ID: a1b2c3d4e5f6
Revises: 25a094b7dccf
Create Date: 2026-02-21 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '25a094b7dccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_token', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('share_expires', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_assessments_share_token'), ['share_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessments_share_token'))
        batch_op.drop_column('share_expires')
        batch_op.drop_column('share_token')

    # ### end Alembic commands ###
