"""add uia integration fields to user

Revision ID: caee37c95edb
Revises: 8cdad1c84069
Create Date: 2026-02-18 10:43:22.577891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caee37c95edb'
down_revision = '8cdad1c84069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uia_user_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('organization', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('uia_role', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_uia_user_id'), ['uia_user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_uia_user_id'))
        batch_op.drop_column('uia_role')
        batch_op.drop_column('organization')
        batch_op.drop_column('uia_user_id')

    # ### end Alembic commands ###
